export type Ingredient = {
  amount: string;
  name: string;
  productSearch?: string; // if set, links to /shop?search=this value
};

export type Recipe = {
  slug: string;
  title: string;
  excerpt: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: "Easy" | "Medium" | "Hard";
  category: string;
  dietTags: string[];
  imageUrl: string;
  ingredients: Ingredient[];
  steps: string[];
  notes?: string;
};

export const RECIPES: Recipe[] = [
  // ── BREAKFAST ──────────────────────────────────────────────────
  {
    slug: "cassava-flour-pancakes",
    title: "Fluffy Cassava Flour Pancakes",
    excerpt: "Light, golden AIP pancakes made with cassava flour and coconut milk — comfort food without the gluten or eggs.",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    category: "Breakfast",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Grain Free"],
    imageUrl: "",
    ingredients: [
      { amount: "1 cup", name: "cassava flour", productSearch: "Otto's Naturals Cassava Flour" },
      { amount: "1 cup", name: "full-fat coconut milk", productSearch: "Thai Kitchen Coconut Milk" },
      { amount: "2 tbsp", name: "coconut oil, melted", productSearch: "Nutiva Organic Coconut Oil" },
      { amount: "1 tbsp", name: "pure maple syrup", productSearch: "NOW Foods Real Maple Syrup" },
      { amount: "1 tsp", name: "pure vanilla extract", productSearch: "Simply Organic Vanilla Extract" },
      { amount: "½ tsp", name: "baking soda" },
      { amount: "¼ tsp", name: "fine sea salt" },
      { amount: "1 tbsp", name: "apple cider vinegar", productSearch: "Bragg Apple Cider Vinegar" },
    ],
    steps: [
      "Whisk together cassava flour, baking soda, and salt in a medium bowl.",
      "In a separate bowl combine coconut milk, melted coconut oil, maple syrup, and vanilla.",
      "Pour the wet ingredients into the dry and stir until just combined. Add apple cider vinegar and stir once more — the batter will slightly thicken.",
      "Heat a non-stick skillet or griddle over medium heat. Lightly grease with coconut oil.",
      "Pour ¼ cup of batter per pancake. Cook 2–3 minutes until small bubbles appear and edges look set, then flip and cook another 1–2 minutes.",
      "Serve warm topped with fresh berries and a drizzle of maple syrup.",
    ],
    notes: "The apple cider vinegar acts as a binder since there are no eggs. Don't skip it! Batter thickens as it sits — thin with a splash of coconut milk if needed.",
  },
  {
    slug: "sweet-potato-breakfast-hash",
    title: "Sweet Potato Breakfast Hash",
    excerpt: "Hearty hash with ground turkey, sweet potato, and fresh herbs — a filling thyroid-supportive start to the day.",
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "Easy",
    category: "Breakfast",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "1 lb", name: "ground turkey or ground beef" },
      { amount: "2 medium", name: "sweet potatoes, peeled and diced small" },
      { amount: "1 medium", name: "yellow onion, diced" },
      { amount: "2 cloves", name: "garlic, minced" },
      { amount: "2 tbsp", name: "avocado oil", productSearch: "Chosen Foods Avocado Oil" },
      { amount: "1 tsp", name: "dried thyme" },
      { amount: "1 tsp", name: "dried rosemary" },
      { amount: "1 tsp", name: "garlic powder" },
      { amount: "½ tsp", name: "sea salt" },
      { amount: "2 tbsp", name: "fresh parsley, chopped" },
      { amount: "1 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
    ],
    steps: [
      "Heat avocado oil in a large skillet over medium-high heat. Add diced sweet potato and cook 8–10 minutes, stirring occasionally, until lightly browned and tender.",
      "Push sweet potatoes to the side. Add onion and cook 3–4 minutes until softened.",
      "Add garlic and cook 30 seconds until fragrant.",
      "Add ground turkey and break it apart with a spatula. Cook until no longer pink, about 6–8 minutes.",
      "Season with thyme, rosemary, garlic powder, and sea salt. Stir in coconut aminos.",
      "Toss everything together and cook another 2 minutes. Taste and adjust seasoning.",
      "Serve topped with fresh parsley.",
    ],
  },
  {
    slug: "aip-banana-bread",
    title: "AIP Banana Bread",
    excerpt: "Moist, naturally sweet banana bread made with tigernut flour — no eggs, no grains, all comfort.",
    prepTime: 10,
    cookTime: 50,
    servings: 8,
    difficulty: "Easy",
    category: "Breakfast",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Grain Free", "Vegan"],
    imageUrl: "",
    ingredients: [
      { amount: "3 large", name: "very ripe bananas, mashed" },
      { amount: "1½ cups", name: "tigernut flour", productSearch: "Organic Gemini Tigernut Flour" },
      { amount: "¼ cup", name: "arrowroot starch", productSearch: "Anthony's Arrowroot Flour" },
      { amount: "¼ cup", name: "coconut oil, melted", productSearch: "Nutiva Organic Coconut Oil" },
      { amount: "3 tbsp", name: "pure maple syrup", productSearch: "NOW Foods Real Maple Syrup" },
      { amount: "1 tsp", name: "pure vanilla extract", productSearch: "Simply Organic Vanilla Extract" },
      { amount: "1 tsp", name: "cinnamon" },
      { amount: "½ tsp", name: "baking soda" },
      { amount: "¼ tsp", name: "sea salt" },
      { amount: "1 tbsp", name: "apple cider vinegar", productSearch: "Bragg Apple Cider Vinegar" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Grease a standard 9x5 loaf pan with coconut oil.",
      "In a large bowl mash the bananas thoroughly until smooth.",
      "Whisk in melted coconut oil, maple syrup, and vanilla.",
      "In a separate bowl combine tigernut flour, arrowroot, cinnamon, baking soda, and salt.",
      "Fold dry ingredients into the banana mixture until just combined. Stir in apple cider vinegar.",
      "Pour batter into the prepared loaf pan and smooth the top.",
      "Bake 45–55 minutes until a toothpick inserted in the center comes out clean.",
      "Cool in pan for 10 minutes before transferring to a wire rack. Cool completely before slicing.",
    ],
    notes: "The riper the bananas, the sweeter and more moist the bread. Overripe bananas with black spots are ideal.",
  },

  // ── LUNCH ────────────────────────────────────────────────────────
  {
    slug: "chicken-avocado-lettuce-wraps",
    title: "Chicken & Avocado Lettuce Wraps",
    excerpt: "Crisp butter lettuce cups filled with shredded chicken, creamy avocado, and a lemon-herb drizzle.",
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    category: "Lunch",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "2 cups", name: "cooked shredded chicken (rotisserie works great)" },
      { amount: "1 head", name: "butter lettuce, leaves separated" },
      { amount: "2 large", name: "ripe avocados, sliced" },
      { amount: "1 medium", name: "cucumber, thinly sliced" },
      { amount: "¼ cup", name: "shredded purple cabbage" },
      { amount: "2 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "2 tbsp", name: "avocado oil", productSearch: "Chosen Foods Avocado Oil" },
      { amount: "1 tbsp", name: "fresh lemon juice" },
      { amount: "1 tsp", name: "garlic powder" },
      { amount: "2 tbsp", name: "fresh cilantro, chopped" },
      { amount: "½ tsp", name: "sea salt" },
    ],
    steps: [
      "In a small bowl whisk together coconut aminos, avocado oil, lemon juice, garlic powder, and salt.",
      "Toss the shredded chicken with half the dressing.",
      "Lay out butter lettuce cups on a serving plate.",
      "Fill each cup with chicken, avocado slices, cucumber, and purple cabbage.",
      "Drizzle with remaining dressing and top with fresh cilantro.",
      "Serve immediately.",
    ],
  },
  {
    slug: "zucchini-noodle-avocado-pesto",
    title: "Zucchini Noodles with Avocado Pesto",
    excerpt: "Spiralized zucchini tossed in creamy avocado pesto — light, fresh, and loaded with healthy fats.",
    prepTime: 15,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    category: "Lunch",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Vegan", "Grain Free"],
    imageUrl: "",
    ingredients: [
      { amount: "4 medium", name: "zucchini, spiralized or peeled into ribbons" },
      { amount: "2 large", name: "ripe avocados" },
      { amount: "1 cup", name: "fresh basil leaves" },
      { amount: "3 tbsp", name: "avocado oil", productSearch: "Chosen Foods Avocado Oil" },
      { amount: "2 tbsp", name: "fresh lemon juice" },
      { amount: "2 cloves", name: "garlic" },
      { amount: "½ tsp", name: "sea salt" },
      { amount: "2 tbsp", name: "nutritional yeast (optional, omit for strict AIP)", productSearch: "Bragg Nutritional Yeast" },
      { amount: "1 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "½ cup", name: "cherry tomatoes, halved (omit for AIP elimination phase)" },
    ],
    steps: [
      "Make the pesto: blend avocados, basil, avocado oil, lemon juice, garlic, and sea salt in a food processor until smooth and creamy. Adjust salt and lemon to taste.",
      "Heat a large skillet over medium-high heat with a drizzle of avocado oil.",
      "Add zucchini noodles and toss for 2–3 minutes just until slightly softened but still with a bite. Don't overcook.",
      "Remove from heat and immediately toss with the avocado pesto and coconut aminos.",
      "Plate and top with cherry tomatoes if using.",
      "Serve right away.",
    ],
    notes: "Eat immediately — zucchini releases water quickly and the pesto will thin out if it sits too long.",
  },

  // ── DINNER ────────────────────────────────────────────────────────
  {
    slug: "sheet-pan-lemon-herb-chicken",
    title: "Sheet Pan Lemon Herb Chicken & Veggies",
    excerpt: "One-pan roasted chicken thighs with seasonal vegetables and healing herbs — minimal cleanup, maximum flavor.",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    difficulty: "Easy",
    category: "Dinner",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "4 large", name: "bone-in, skin-on chicken thighs" },
      { amount: "2 medium", name: "sweet potatoes, cubed" },
      { amount: "2 cups", name: "broccoli florets" },
      { amount: "1 medium", name: "red onion, wedged" },
      { amount: "3 tbsp", name: "avocado oil", productSearch: "Chosen Foods Avocado Oil" },
      { amount: "3 tbsp", name: "fresh lemon juice" },
      { amount: "1 tbsp", name: "lemon zest" },
      { amount: "4 cloves", name: "garlic, minced" },
      { amount: "1 tsp", name: "dried thyme" },
      { amount: "1 tsp", name: "dried rosemary" },
      { amount: "1 tsp", name: "dried oregano" },
      { amount: "1 tsp", name: "sea salt" },
      { amount: "2 tbsp", name: "fresh parsley, chopped (for serving)" },
    ],
    steps: [
      "Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.",
      "Whisk together avocado oil, lemon juice, lemon zest, garlic, thyme, rosemary, oregano, and salt.",
      "Add sweet potato and red onion to the pan. Toss with half the marinade. Push to the edges.",
      "Place chicken thighs in the center of the pan. Pour remaining marinade over the chicken.",
      "Roast for 20 minutes. Add broccoli florets to the pan, toss in the pan juices.",
      "Continue roasting another 15–20 minutes until chicken is golden and reaches 165°F internal temp.",
      "Scatter fresh parsley over the top and serve straight from the pan.",
    ],
  },
  {
    slug: "coconut-curry-salmon",
    title: "Coconut Curry Salmon",
    excerpt: "Omega-3 rich salmon in a fragrant, anti-inflammatory coconut curry sauce over cauliflower rice.",
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    category: "Dinner",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "2 (6 oz)", name: "wild-caught salmon fillets" },
      { amount: "1 (13.5 oz) can", name: "full-fat coconut milk", productSearch: "Thai Kitchen Coconut Milk" },
      { amount: "1 tbsp", name: "coconut oil", productSearch: "Nutiva Organic Coconut Oil" },
      { amount: "1 medium", name: "yellow onion, diced" },
      { amount: "4 cloves", name: "garlic, minced" },
      { amount: "1 tbsp", name: "fresh ginger, grated" },
      { amount: "1 tsp", name: "turmeric powder" },
      { amount: "1 tsp", name: "ginger powder" },
      { amount: "1 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "1 tbsp", name: "fresh lime juice" },
      { amount: "2 cups", name: "baby spinach" },
      { amount: "1 tsp", name: "sea salt" },
      { amount: "4 cups", name: "cauliflower rice, for serving" },
    ],
    steps: [
      "Heat coconut oil in a large skillet over medium heat. Add onion and cook 4–5 minutes until soft.",
      "Add garlic and ginger, cook 1 minute until fragrant.",
      "Stir in turmeric and ginger powder, cook 30 seconds.",
      "Pour in coconut milk and coconut aminos. Stir well and bring to a gentle simmer.",
      "Season salmon fillets with salt. Nestle them into the sauce.",
      "Cover and cook 8–10 minutes until salmon is cooked through and flakes easily.",
      "Stir in baby spinach and lime juice. Let spinach wilt, about 1 minute.",
      "Serve over cauliflower rice with extra lime wedges.",
    ],
    notes: "Wild-caught salmon has significantly more omega-3s than farmed. Look for sockeye or king salmon.",
  },
  {
    slug: "slow-cooker-pulled-chicken",
    title: "Slow Cooker AIP Pulled Chicken",
    excerpt: "Fall-apart tender pulled chicken with a tangy AIP-friendly BBQ sauce — perfect for meal prep.",
    prepTime: 10,
    cookTime: 360,
    servings: 6,
    difficulty: "Easy",
    category: "Dinner",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "2 lbs", name: "boneless skinless chicken breasts or thighs" },
      { amount: "1 cup", name: "unsweetened applesauce" },
      { amount: "3 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "2 tbsp", name: "apple cider vinegar", productSearch: "Bragg Apple Cider Vinegar" },
      { amount: "2 tbsp", name: "pure maple syrup", productSearch: "NOW Foods Real Maple Syrup" },
      { amount: "1 tsp", name: "garlic powder" },
      { amount: "1 tsp", name: "onion powder" },
      { amount: "1 tsp", name: "smoked sea salt" },
      { amount: "1 tsp", name: "dried thyme" },
      { amount: "½ tsp", name: "ginger powder" },
    ],
    steps: [
      "Whisk together applesauce, coconut aminos, apple cider vinegar, maple syrup, garlic powder, onion powder, salt, thyme, and ginger.",
      "Place chicken in the slow cooker and pour sauce over the top.",
      "Cook on LOW for 6–8 hours or HIGH for 3–4 hours until chicken is very tender.",
      "Remove chicken and shred with two forks.",
      "Return shredded chicken to the slow cooker and stir to coat with the sauce. Cook uncovered on HIGH for 15 minutes to thicken.",
      "Serve over cauliflower rice, in lettuce wraps, or stuffed into roasted sweet potatoes.",
    ],
    notes: "This freezes beautifully. Portion into containers for up to 3 months.",
  },

  // ── SOUPS & STEWS ──────────────────────────────────────────────
  {
    slug: "turmeric-ginger-bone-broth-soup",
    title: "Turmeric Ginger Healing Soup",
    excerpt: "Anti-inflammatory, gut-healing soup built on bone broth with golden turmeric and warming ginger.",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    category: "Soups & Stews",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Paleo"],
    imageUrl: "",
    ingredients: [
      { amount: "4 cups", name: "chicken bone broth", productSearch: "Kettle & Fire Chicken Bone Broth" },
      { amount: "2 cups", name: "shredded cooked chicken" },
      { amount: "1 medium", name: "yellow onion, diced" },
      { amount: "3 cloves", name: "garlic, minced" },
      { amount: "1 tbsp", name: "fresh ginger, grated" },
      { amount: "1 tsp", name: "turmeric powder" },
      { amount: "1 tbsp", name: "coconut oil", productSearch: "Nutiva Organic Coconut Oil" },
      { amount: "2 medium", name: "carrots, sliced" },
      { amount: "2 stalks", name: "celery, sliced" },
      { amount: "2 cups", name: "baby spinach or kale" },
      { amount: "1 tbsp", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "1 tbsp", name: "fresh lemon juice" },
      { amount: "1 tsp", name: "sea salt" },
    ],
    steps: [
      "Heat coconut oil in a large pot over medium heat. Add onion, carrots, and celery. Cook 5–6 minutes until softened.",
      "Add garlic, ginger, and turmeric. Stir and cook 1 minute until fragrant.",
      "Pour in bone broth and bring to a simmer.",
      "Add shredded chicken and coconut aminos. Simmer 10 minutes.",
      "Stir in spinach or kale and cook until just wilted, about 2 minutes.",
      "Finish with lemon juice and salt. Taste and adjust seasoning.",
      "Ladle into bowls and serve hot.",
    ],
    notes: "The black pepper traditionally paired with turmeric is omitted here for strict AIP. The bone broth itself provides plenty of anti-inflammatory benefit.",
  },

  // ── SMOOTHIES & DRINKS ────────────────────────────────────────
  {
    slug: "thyroid-support-smoothie",
    title: "Thyroid Support Green Smoothie",
    excerpt: "A nourishing blend of anti-inflammatory ingredients designed to support thyroid and adrenal health.",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    category: "Smoothies & Drinks",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Vegan"],
    imageUrl: "",
    ingredients: [
      { amount: "1 cup", name: "full-fat coconut milk", productSearch: "Thai Kitchen Coconut Milk" },
      { amount: "1 cup", name: "filtered water or coconut water" },
      { amount: "1 medium", name: "frozen banana" },
      { amount: "1 cup", name: "frozen mango chunks" },
      { amount: "1 tsp", name: "turmeric powder" },
      { amount: "½ tsp", name: "ginger powder" },
      { amount: "1 tbsp", name: "pure maple syrup (optional)", productSearch: "NOW Foods Real Maple Syrup" },
      { amount: "1 tbsp", name: "collagen peptides (optional)", productSearch: "Vital Proteins Collagen Peptides" },
      { amount: "1 tsp", name: "pure vanilla extract", productSearch: "Simply Organic Vanilla Extract" },
      { amount: "pinch", name: "sea salt" },
    ],
    steps: [
      "Add all ingredients to a high-speed blender.",
      "Blend on high for 60 seconds until completely smooth and creamy.",
      "Taste and adjust sweetness with maple syrup if needed.",
      "Pour into a glass and serve immediately.",
    ],
    notes: "The fat from coconut milk helps your body absorb the curcumin in turmeric. Don't skip it!",
  },

  // ── SNACKS ────────────────────────────────────────────────────
  {
    slug: "cucumber-avocado-bites",
    title: "Cucumber Avocado Bites",
    excerpt: "Cool, creamy, and anti-inflammatory — a 5-minute snack that actually keeps you full.",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    category: "Snacks",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Vegan"],
    imageUrl: "",
    ingredients: [
      { amount: "1 large", name: "English cucumber, sliced into rounds" },
      { amount: "2 large", name: "ripe avocados" },
      { amount: "1 tbsp", name: "fresh lemon juice" },
      { amount: "1 tsp", name: "garlic powder" },
      { amount: "½ tsp", name: "sea salt" },
      { amount: "2 tbsp", name: "fresh chives or parsley, chopped" },
      { amount: "1 tsp", name: "coconut aminos (optional)", productSearch: "Coconut Secret Coconut Aminos" },
    ],
    steps: [
      "Mash avocados with lemon juice, garlic powder, and salt until smooth but still slightly chunky.",
      "Stir in coconut aminos if using.",
      "Arrange cucumber rounds on a plate.",
      "Spoon or pipe a dollop of avocado onto each cucumber round.",
      "Top with fresh chives or parsley and a pinch of sea salt.",
      "Serve immediately.",
    ],
  },

  // ── SAUCES & CONDIMENTS ────────────────────────────────────────
  {
    slug: "aip-coconut-aminos-dipping-sauce",
    title: "AIP Ginger Dipping Sauce",
    excerpt: "A versatile, umami-rich sauce using coconut aminos and fresh ginger — perfect for wraps, chicken, and more.",
    prepTime: 5,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    category: "Sauces & Condiments",
    dietTags: ["AIP", "Gluten Free", "Dairy Free", "Vegan"],
    imageUrl: "",
    ingredients: [
      { amount: "¼ cup", name: "coconut aminos", productSearch: "Coconut Secret Coconut Aminos" },
      { amount: "2 tbsp", name: "fresh lime juice" },
      { amount: "1 tbsp", name: "avocado oil", productSearch: "Chosen Foods Avocado Oil" },
      { amount: "1 tsp", name: "fresh ginger, grated" },
      { amount: "1 tsp", name: "garlic powder" },
      { amount: "1 tsp", name: "pure maple syrup", productSearch: "NOW Foods Real Maple Syrup" },
      { amount: "1 tbsp", name: "apple cider vinegar", productSearch: "Bragg Apple Cider Vinegar" },
    ],
    steps: [
      "Whisk all ingredients together in a small bowl.",
      "Taste and adjust — more lime for brightness, more maple syrup for sweetness, more ginger for heat.",
      "Store in a sealed jar in the refrigerator for up to 1 week.",
    ],
    notes: "Doubles as a marinade for chicken or salmon. Brush it on before roasting for incredible flavor.",
  },
];

export const RECIPE_CATEGORIES = [
  "All Recipes", "Breakfast", "Lunch", "Dinner",
  "Snacks", "Soups & Stews", "Smoothies & Drinks", "Sauces & Condiments",
];
